# Generated by Django 3.2.6 on 2021-10-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='thumb',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
