# Generated by Django 3.2.6 on 2021-10-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_articles_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='thumb',
            new_name='base_image',
        ),
    ]
