# Generated by Django 3.2.6 on 2021-10-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_thumb_articles_base_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='slug',
            new_name='article_slug',
        ),
    ]
