# Generated by Django 3.2.6 on 2021-10-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_slug_articles_article_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='article_slug',
            new_name='slug',
        ),
    ]
